Update vm import progress reflect dv import
kubevirt/vm-import-operator pull request #204
Opened 2020-05-12 07:48 UTC by machacekondra

Fixes: https://github.com/kubevirt/vm-import-operator/issues/126
Fixes: https://github.com/kubevirt/vm-import-operator/issues/124

Since CDI v1.17.0 imageio progress is updated for the DV import.
This patch changes the update progress of the VM import to following
format:

1) start at 10 if validation is successfull
2) count progress as 10 + (allDvProgress / countOfDisks) * (75 / 100)
3) if all disks import is done we are at 85
4) Start vm 90
5) Finish 100

So for example for two disks of one done on 25% and second for 60%
we go as -> 10 + (85 / 2) * 0.75 = 41.875%

Signed-off-by: Ondra Machacek <omachace@redhat.com>

2020-05-12 08:00 UTC, pkliczewski approved these changes
Looks good, would be good to add a test or two :)

2020-05-13 07:52 UTC, jakub-dzon requested changes

2020-05-13 07:52 UTC, jakub-dzon commented on pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
> +	progressForCopyDisk               = 75
Could you, please, group this with other `progress*` constants?

2020-05-13 09:09 UTC, masayag approved these changes

2020-05-13 10:19 UTC, jakub-dzon approved these changes

2020-05-13 10:19 UTC, merged