Functional tests for invalid image
kubevirt/vm-import-operator pull request #263
Opened 2020-05-28 13:09 UTC by machacekondra

Signed-off-by: Ondra Machacek <omachace@redhat.com>

2020-05-28 13:45 UTC, jakub-dzon requested changes

2020-05-28 13:45 UTC, jakub-dzon commented on tests/ovirt/basic_vm_import_negative_test.go
> +		err = f.OvirtStubbingClient.Reset("static-sso,static-transfer,static-namespace,static-transfers")
It is already in the common BeforeEach (https://github.com/kubevirt/vm-import-operator/blob/ec9095c98ca3b4c627ad68511871611508ea9cb0/tests/framework/framework.go#L176)

2020-05-28 16:30 UTC, machacekondra commented
/retest

2020-05-29 05:42 UTC, machacekondra commented
/retest

2020-05-29 07:14 UTC, jakub-dzon approved these changes

2020-05-29 07:14 UTC, jakub-dzon commented
/test pull-vm-import-operator-e2e-k8s-1.16

2020-05-29 08:08 UTC, pkliczewski commented
/retest

2020-05-29 14:13 UTC, pkliczewski approved these changes

2020-05-29 14:13 UTC, merged