Fix func tests for kubevirt v0.30.4
kubevirt/vm-import-operator pull request #338
Opened 2020-07-14 08:49 UTC by machacekondra

Since kubevirt v0.30.4 secure boot is enabled by default for the EFI
bootloader, so we need to enable SMM, for EFI bootloaders.

Signed-off-by: Ondra Machacek <omachace@redhat.com>

2020-07-14 11:49 UTC, pkliczewski approved these changes

2020-07-14 11:58 UTC, jakub-dzon requested changes

2020-07-14 11:58 UTC, jakub-dzon commented on pkg/providers/ovirt/mapper/mapper.go
> +func (o *OvirtMapper) mapFeatures() *kubevirtv1.Features {
Please add proper check in the unit test.

2020-07-14 13:41 UTC, jakub-dzon commented on pkg/providers/ovirt/mapper/mapper_test.go
> +			Expect(vmSpec.Spec.Template.Spec.Domain.Features).ToNot(BeNil())
That check can be moved before if - the other branch assumes that `vmSpec.Spec.Template.Spec.Domain.Features` are not nil.

2020-07-15 06:15 UTC, jakub-dzon approved these changes

2020-07-15 08:43 UTC, merged