Allow to import vms using i440fx bios
kubevirt/vm-import-operator pull request #364
Opened 2020-08-07 13:23 UTC by pkliczewski

We required a user to make sure that source vm uses q35 compatibile bios. Changing the bios do not modify the quest but it may affect device layout upon reboot. We should not affect source vm while importing. This PR allows to import i440fx in the same way as q35.

Signed-off-by: Piotr Kliczewski <piotr.kliczewski@gmail.com>

2020-08-10 07:03 UTC, jakub-dzon requested changes

2020-08-10 07:03 UTC, jakub-dzon commented on tests/ovirt/vm_validation_test.go
> -		table.Entry("unsupported i440fx_sea_bios BIOS type", vms.UnsupportedBiosTypeVmID, "bios-type-template.xml", map[string]string{"@BIOSTYPE": "i440fx_sea_bios"}),
Please add a test case for i440fx_sea_bios to https://github.com/kubevirt/vm-import-operator/blob/4123ab618dec72f41bbba540bf19d6e7f1c6b151/tests/ovirt/various_vm_configurations_test.go#L96

2020-08-10 07:22 UTC, machacekondra approved these changes

2020-08-11 09:34 UTC, jakub-dzon approved these changes
LGTM. Let's just wait for the tests to pass.

2020-08-11 10:21 UTC, masayag approved these changes

2020-08-11 11:42 UTC, merged