Add mapping merger for the VMWare provider
kubevirt/vm-import-operator pull request #377
Opened 2020-08-18 19:12 UTC by mansam

This also refactors some of the ovirt mapping-merger code into a common location where it can be shared between providers.

Signed-off-by: Sam Lucidi <slucidi@redhat.com>

2020-08-19 07:04 UTC, jakub-dzon requested changes

2020-08-19 07:04 UTC, jakub-dzon commented on pkg/mappings/merger.go
> +func MergeNetworkMappings(primaryMappings *[]v1beta1.NetworkResourceMappingItem, secondaryMappings *[]v1beta1.NetworkResourceMappingItem) *[]v1beta1.NetworkResourceMappingItem {
Please add comment; the function is exported.

2020-08-19 07:04 UTC, jakub-dzon commented on pkg/mappings/merger.go
> +func MergeStorageMappings(primaryMappings *[]v1beta1.StorageResourceMappingItem, secondaryMappings *[]v1beta1.StorageResourceMappingItem) *[]v1beta1.StorageResourceMappingItem {
Please add comment; the function is exported.

2020-08-19 14:27 UTC, jakub-dzon approved these changes

2020-08-20 10:20 UTC, pkliczewski approved these changes

2020-08-20 10:20 UTC, merged