vSphere: always map machine type to q35
kubevirt/vm-import-operator pull request #429
Opened 2020-10-22 19:43 UTC by mansam

This overwrites the machine type that might be set by the template the VM is based on, in order to avoid the VM failing to start due to an unsupported machine type.

Signed-off-by: Sam Lucidi <slucidi@redhat.com>

2020-10-23 06:55 UTC, jakub-dzon requested changes

2020-10-23 06:55 UTC, jakub-dzon commented on pkg/providers/vmware/mapper/mapper.go
> +	vmSpec.Spec.Template.Spec.Domain.Machine = kubevirtv1.Machine{Type: q35}
Please have it verified/"documented" by a unit test so that wouldn't get changed accidentally later.

2020-10-23 17:25 UTC, mansam commented
/retest

2020-10-25 14:23 UTC, pkliczewski commented
@mansam Please take a look at test failure where:

> Error converting guests: virt-v2v job vmimport.v2v.kubevirt.iorzll9 failed

we need to understand what is the reason.

2020-10-26 19:08 UTC, mansam commented
Still trying to determine the cause of this test failure. The tests pass on my development machine, and all of the test vms use the same disk images via the fake vddk, so if guest conversion passes for one it should pass for all of them.

2020-10-27 13:19 UTC, mansam commented
/retest

2020-10-28 12:05 UTC, pkliczewski approved these changes

2020-10-28 12:19 UTC, jakub-dzon approved these changes

2020-10-28 12:19 UTC, merged